In [1]:
import numpy as np

In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Javi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Javi/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Javi/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/User

In [11]:
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [14]:
a = np.arange(10, 50)

In [15]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [22]:
np.random.random((3,3,3))

array([[[0.86175745, 0.70689263, 0.75978492],
        [0.96056142, 0.43518468, 0.92942554],
        [0.97782327, 0.58661418, 0.10189813]],

       [[0.67605572, 0.86433752, 0.20866523],
        [0.0239993 , 0.87482676, 0.60048334],
        [0.7036231 , 0.61539794, 0.25608223]],

       [[0.77222951, 0.41046345, 0.73642896],
        [0.0137409 , 0.25398678, 0.31585177],
        [0.36709477, 0.66557565, 0.35509987]]])

In [38]:
a = np.random.random((10,10)).round(2)
print(a)
print(np.max(a))
print(np.min(a))

[[0.21 0.91 0.61 0.29 0.42 0.02 0.73 0.83 0.19 0.23]
 [0.92 0.65 0.86 0.13 0.69 0.7  0.77 0.46 0.13 0.34]
 [0.46 0.46 0.78 0.69 0.39 0.85 0.24 0.35 0.23 0.04]
 [0.61 0.27 0.38 0.53 0.43 0.56 0.94 0.9  0.05 0.72]
 [0.11 0.27 0.25 0.84 0.54 0.71 0.66 0.43 0.31 0.54]
 [0.   0.32 0.28 0.39 0.5  0.89 0.71 0.14 0.15 0.39]
 [0.59 0.82 0.22 0.52 0.23 0.06 0.57 0.07 0.24 0.88]
 [0.64 0.55 0.2  0.15 0.71 0.05 1.   0.73 0.79 0.61]
 [0.98 0.27 0.4  0.03 0.72 0.   0.02 0.51 0.07 0.86]
 [0.91 0.83 0.83 0.09 0.08 0.63 0.49 0.36 0.78 0.95]]
1.0
0.0


In [41]:
a = np.zeros((10,10))
a[1:-1, 1:-1] = 1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
b = np.ones((10,10))
b[:, [0,-1]] = 0
b[[0,-1], :] = 0
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
np.nan in set([np.nan])

True

In [60]:
30 == 10 * 3

True

In [61]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [66]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [82]:
z = np.zeros((8,8),dtype=int)
z[1::2, ::2] = 5
z[::2, 1::2] = 5
print(z)

[[0 5 0 5 0 5 0 5]
 [5 0 5 0 5 0 5 0]
 [0 5 0 5 0 5 0 5]
 [5 0 5 0 5 0 5 0]
 [0 5 0 5 0 5 0 5]
 [5 0 5 0 5 0 5 0]
 [0 5 0 5 0 5 0 5]
 [5 0 5 0 5 0 5 0]]


In [84]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [92]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
np.tile(np.array([[1,0], [0,1]]), (2,2))

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [4]:
10000 ** 100 < np.inf

True