In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([[1.0,2.0,3.0], [4.0,5.0,6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [7]:
# Get total size
a.nbytes

12

### Accessing specific elements, rows, columns...

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
# Get specific element [r, c]
a[1, 4]

12

In [10]:
# Get an specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [11]:
# Get an specific column
a[:, 4]

array([ 5, 12])

In [12]:
# Getting fancy [startindex, endindex: stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [13]:
# Changing specific values
a[1,4] = 20
print(a)

a[:, 5] = [25,35]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]
[[ 1  2  3  4  5 25  7]
 [ 8  9 10 11 20 35 14]]


Quik 3-d example.

In [14]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
# Getting a specific element(s)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [16]:
# Replacing
b[:,0,:] = [[8,8],[9,9]]
b

array([[[8, 8],
        [3, 4]],

       [[9, 9],
        [7, 8]]])

### Initiliazing different types of arrays

In [17]:
# All 0s matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# All ones matrix
np.ones((2,4,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [58]:
# Identity matrix
np.identity(3)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
# Any other value
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [65]:
print(np.arange(20))
print(np.arange(1, 20, 3))
print(np.arange(10000).reshape(100,100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  4  7 10 13 16 19]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [21]:
# Any other value (full_like)
print(a)
np.full_like(a, 4)

[[ 1  2  3  4  5 25  7]
 [ 8  9 10 11 20 35 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random float numbers matrix
np.random.rand(4,3)

array([[0.13751738, 0.64413759, 0.65268999],
       [0.20055702, 0.29532329, 0.67051989],
       [0.16495475, 0.50369186, 0.80048897],
       [0.1764711 , 0.3604    , 0.56230649]])

In [23]:
# Random integers numbers matrix
np.random.randint(1, 7, size=(3,5))

array([[1, 3, 4, 5, 5],
       [1, 1, 3, 1, 5],
       [2, 6, 2, 2, 6]])

In [24]:
# Challenge.
ones = np.ones((5,5))
zeros = np.zeros((3,3))

zeros[1,1] = 9

ones[1:4, 1:4] = zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying arrays

In [25]:
a = np.array([1, 2, 3])
b = a.copy()
b[1] = 19
print(a)
print(b)

[1 2 3]
[ 1 19  3]


### Mathematics

In [26]:
a = np.array([1,2,3,4])

In [27]:
a + 2

array([3, 4, 5, 6])

In [28]:
a - 2

array([-1,  0,  1,  2])

In [29]:
a * 2

array([2, 4, 6, 8])

In [30]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [31]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [32]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [33]:
a * b

array([1, 0, 3, 0])

In [34]:
# Take the sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [35]:
# Take the cos of all values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [36]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [37]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2.5)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2.5 2.5]
 [2.5 2.5]
 [2.5 2.5]]


In [38]:
# Multiplying matrix
np.matmul(a, b)

array([[7.5, 7.5],
       [7.5, 7.5]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [40]:
d = np.random.randint(-4, 8, (3,3))
print(d)
print(np.linalg.det(d).round(2))
np.linalg.inv(d)

[[-2  3 -1]
 [-4  1  7]
 [-3  4  5]]
56.0


array([[-0.41071429, -0.33928571,  0.39285714],
       [-0.01785714, -0.23214286,  0.32142857],
       [-0.23214286, -0.01785714,  0.17857143]])

In [41]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [42]:
stats = np.array([[1, 2, 30], [4, 8, 6]])
stats

array([[ 1,  2, 30],
       [ 4,  8,  6]])

In [43]:
np.min(stats)

1

In [44]:
np.min(stats, axis=0)

array([1, 2, 6])

In [45]:
np.max(stats)

30

In [46]:
np.max(stats, axis=1)

array([30,  8])

In [47]:
np.mean(stats)

8.5

In [48]:
np.sum(stats)

51

### Reorganizing arrays

In [49]:
arr_1 = np.array([[1,2,3], [6,7,8]])
print(arr_1)

arr_2 = arr_1.reshape((3,2))
print(arr_2)

[[1 2 3]
 [6 7 8]]
[[1 2]
 [3 6]
 [7 8]]


In [50]:
# Traspuesta
arr_1.T

array([[1, 6],
       [2, 7],
       [3, 8]])

In [51]:
# Vertical stacking vectors
v1 = np.array([10, 20, 30, 40])
v2 = np.array([4, 8, 2, 9])
v3 = np.array([[1,2,3,4],[5,6,7,8]])

np.vstack([v1, v2, v1, v3])

array([[10, 20, 30, 40],
       [ 4,  8,  2,  9],
       [10, 20, 30, 40],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [52]:
# Horizontal stacking vectors

In [53]:
h1 = np.ones((2,3))
h2 = np.zeros((2,4))

np.hstack((h1, h2))

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

# Miscellaneous

### Load data from a file

In [54]:
file_data = np.genfromtxt('data.txt', delimiter=',')
print(file_data)
file_int = file_data.astype('int32')
file_int

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking & Advanced indexing

In [55]:
file_int > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [56]:
file_int[file_int > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [57]:
((file_int > 50) & (file_int < 100))
# doing the reverse. "~" means not.
(~((file_int > 50) & (file_int < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

### Exercises

**Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [5]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**Create a 8x8 matrix and fill it with a checkerboard pattern**

In [6]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**np.tile(A, reps)**   Construct an array by repeating A the number of times given by reps.

In [8]:
np.tile([1,0], (2,3))

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [9]:
x = np.array([[0,1],[1,0]])

y = np.tile(x, (4,4))
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a matrix shape like the given one, and fill it with:
- bottom-left triangle: 0
- top-righ triangle: 1
<br>
¬¬¬ x = np.random.randint(-2, 4, size=(6, 6))

In [14]:
x = np.random.randint(-2, 4, size=(6, 6))
np.zeros_like(x)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])